"""
app/models/model_registry.py
-----------------------------
Model versioning and loading.

Supports multiple model versions coexisting on disk.
The active version is selected via settings.MODEL_VERSION.
"""

from __future__ import annotations

import pickle
from pathlib import Path
from typing import Dict, Optional

import torch
from sklearn.ensemble import RandomForestClassifier

from app.core.config import settings
from app.core.logging import logger
from ml.training.cnn_model import SeizureCNN


class ModelRegistry:
    """
    Central registry that manages model artefacts.

    Design pattern: registry singleton held by the FastAPI lifespan context.
    """

    def __init__(self) -> None:
        self._cnn_models:  Dict[str, SeizureCNN]           = {}
        self._rf_models:   Dict[str, RandomForestClassifier] = {}
        self._cnn_metadata: Dict[str, dict] = {}
        self._active_version: str = settings.MODEL_VERSION

    # ── CNN ───────────────────────────────────────────────────────────────────

    def load_cnn(
        self,
        version: Optional[str] = None,
        path: Optional[Path] = None,
    ) -> SeizureCNN:
        ver       = version or self._active_version
        load_path = path or (settings.MODEL_DIR / f"{settings.MODEL_NAME}_{ver}.pt")

        if not load_path.exists():
            raise FileNotFoundError(f"CNN model not found: {load_path}")

        # Checkpoints are generated by this local training pipeline and include
        # metadata beyond raw tensor weights, so opt out of PyTorch 2.6's
        # stricter default loader mode here.
        checkpoint  = torch.load(load_path, map_location="cpu", weights_only=False)
        cfg         = checkpoint.get("model_config", {
            "n_channels":  settings.N_CHANNELS,
            "window_size": settings.WINDOW_SIZE,
        })
        model = SeizureCNN(**cfg)
        model.load_state_dict(checkpoint["model_state_dict"])
        model.eval()

        self._cnn_models[ver] = model
        self._cnn_metadata[ver] = {
            "model_config": checkpoint.get("model_config", {}),
            "training_config": checkpoint.get("training_config", {}),
        }
        logger.info("CNN model loaded | version={} | path={}", ver, load_path)
        return model

    def get_cnn(self, version: Optional[str] = None) -> SeizureCNN:
        ver = version or self._active_version
        if ver not in self._cnn_models:
            return self.load_cnn(version=ver)
        return self._cnn_models[ver]

    # ── RandomForest ──────────────────────────────────────────────────────────

    def load_rf(
        self,
        version: Optional[str] = None,
        path: Optional[Path] = None,
    ) -> RandomForestClassifier:
        ver       = version or self._active_version
        load_path = path or (settings.MODEL_DIR / f"rf_seizure_detector_{ver}.pkl")

        if not load_path.exists():
            raise FileNotFoundError(f"RF model not found: {load_path}")

        with open(load_path, "rb") as f:
            model = pickle.load(f)

        self._rf_models[ver] = model
        logger.info("RF model loaded | version={} | path={}", ver, load_path)
        return model

    def get_rf(self, version: Optional[str] = None) -> RandomForestClassifier:
        ver = version or self._active_version
        if ver not in self._rf_models:
            return self.load_rf(version=ver)
        return self._rf_models[ver]

    # ── Utility ───────────────────────────────────────────────────────────────

    def list_versions(self) -> Dict[str, list]:
        cnn_versions = [p.stem.split("_")[-1] for p in settings.MODEL_DIR.glob(f"{settings.MODEL_NAME}_*.pt")]
        rf_versions  = [p.stem.split("_")[-1] for p in settings.MODEL_DIR.glob("rf_seizure_detector_*.pkl")]
        return {"cnn": cnn_versions, "rf": rf_versions}

    def get_cnn_metadata(self, version: Optional[str] = None) -> dict:
        ver = version or self._active_version
        if ver not in self._cnn_models:
            self.load_cnn(version=ver)
        return self._cnn_metadata.get(ver, {})

    @property
    def active_version(self) -> str:
        return self._active_version

    def set_active_version(self, version: str) -> None:
        self._active_version = version
        logger.info("Active model version set to: {}", version)


# Application-level singleton
registry = ModelRegistry()
